Added if statwmwnt on deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -93,8 +93,11 @@ jobs:
           kubectl rollout status deployment/prod-app -n app-ns
       - name: Apply updated Kubernetes manifest
         run: |
-          kubectl apply -f ./k8s/deployment.yaml
-          kubectl rollout status deployment/prod-app -n app-ns || echo "K8S_FAILED=true" >> $GITHUB_ENV
+          set -e
+          if ! kubectl apply -f ./k8s; then
+            echo "K8S_FAILED=true" >> $GITHUB_ENV
+            exit 1
+          fi
   approval:
     if: ${{ env.K8S_FAILED == 'true' }}
     needs: deploy
